version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        links:
            - php7
        working_dir: /var/www/html

    php7:
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        container_name: php7
        working_dir: /var/www/html
